### ISSUE TITLE
🚀 Release Tracking Issue: v0.1.0

### ISSUE THREAD

**Issue by jwdunne** [jwdunne/enguard#11]
**What is the goal of the project**?
Release the first working version of Enguard.

**Tasks:**

- [x] #1 - Write the README
- [x] #5 - Setup mypy
- [x] Setup setup.py
- [x] Setup dev dependencies
- [x] Configure flake8
- [x] Configure black
- [x] Set up 'check' script that runs mypy, flake8
- [ ] Sketch out what the watch mode interface should look like
- [ ] Insert example run gif
- [x] Expand configuration example with working Python code
- [x] Fix failing mypy errors
- [x] Configure CI (GitHub Actions?)

*I need to expand this - writing the README will tell me what features I need*
