### ISSUE TITLE
🚀 Set up experiments using tests 

### ISSUE THREAD

**Issue by jwdunne** [jwdunne/enguard#4]
**What is the goal of the project**?
I need to validate my ideas on how to solve certain problems. I can use the code and results as a reference for feature implementation.

**Tasks:**
- [x] Set up experiments module and tests
- [x] Getting list of files changed for incoming commit
- [x] #17 - Acceptance testing a CLI
- [x] #13 - Registering githooks
- [ ] #14 - Getting list of files changed between current push and previous
- [ ] #15 - Getting list of files incoming in a merge
- [ ] #16 - Enforcing code coverage 
- [x] Creating and tearing down a fake git repo
